/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import javax.swing.JFrame;

/**
 *
 * @author dsdd
 */
public class InterfaceAdm extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceAdm
     */
    public InterfaceAdm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelFecharLogin1 = new javax.swing.JLabel();
        jLabelMinLogin1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnRelatório = new javax.swing.JButton();
        btnCadastroUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(248, 148, 6));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Olá! Seja bem vindo(a)!");

        jLabelFecharLogin1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelFecharLogin1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecharLogin1.setText("X");
        jLabelFecharLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFecharLogin1MouseClicked(evt);
            }
        });

        jLabelMinLogin1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMinLogin1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinLogin1.setText("-");
        jLabelMinLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinLogin1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabelMinLogin1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFecharLogin1)
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecharLogin1)
                    .addComponent(jLabelMinLogin1)
                    .addComponent(jLabel3))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 400, 70);

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setLayout(null);

        btnRelatório.setBackground(new java.awt.Color(108, 122, 137));
        btnRelatório.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRelatório.setForeground(new java.awt.Color(236, 240, 241));
        btnRelatório.setText("Relatório");
        btnRelatório.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatórioActionPerformed(evt);
            }
        });
        jPanel2.add(btnRelatório);
        btnRelatório.setBounds(110, 40, 170, 30);

        btnCadastroUsuarios.setBackground(new java.awt.Color(108, 122, 137));
        btnCadastroUsuarios.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCadastroUsuarios.setForeground(new java.awt.Color(236, 240, 241));
        btnCadastroUsuarios.setText("Gerenciar usuários");
        btnCadastroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroUsuariosActionPerformed(evt);
            }
        });
        jPanel2.add(btnCadastroUsuarios);
        btnCadastroUsuarios.setBounds(80, 130, 230, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 400, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelFecharLogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFecharLogin1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelFecharLogin1MouseClicked

    private void jLabelMinLogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinLogin1MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinLogin1MouseClicked

    private void btnCadastroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroUsuariosActionPerformed
       InterfaceADMCadastraCUsuários admcuser = new InterfaceADMCadastraCUsuários();
        admcuser.setVisible(true);
        admcuser.pack();
        admcuser.setLocationRelativeTo(null);
        admcuser.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnCadastroUsuariosActionPerformed

    private void btnRelatórioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatórioActionPerformed
       InterfaceAdmRelatorio admrel = new InterfaceAdmRelatorio();
        admrel.setVisible(true);
        admrel.pack();
        admrel.setLocationRelativeTo(null);
        admrel.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnRelatórioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroUsuarios;
    private javax.swing.JButton btnRelatório;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFecharLogin1;
    private javax.swing.JLabel jLabelMinLogin1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
