/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import USUARIOS.Login;
import java.util.ArrayList;
import javax.swing.JFrame;
import java.util.Arrays;
import javax.swing.JOptionPane;


/**
 *
 * @author dsdd
 */
public class InterfaceLogin extends javax.swing.JFrame {

    private ArrayList<Login> listaLogin;

    /**
     * Creates new form InterfaceLogin
     */
    public InterfaceLogin() {
        initComponents();
        this.setLocationRelativeTo(this);
        listaLogin = new ArrayList(Arrays.asList(listaLogin));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFecharLogin = new javax.swing.JLabel();
        jLabelMinLogin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelLoginPgLogin = new javax.swing.JLabel();
        jLabelSenhaPgLogin = new javax.swing.JLabel();
        txtLoginPgLogin = new javax.swing.JTextField();
        txtSenhaPgLogin = new javax.swing.JPasswordField();
        jButtonCancelarPgLogin = new javax.swing.JButton();
        jButtonEntrarPgLogin = new javax.swing.JButton();
        cbUsuario = new javax.swing.JComboBox<>();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tela de Acesso");

        jLabelFecharLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelFecharLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecharLogin.setText("X");
        jLabelFecharLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFecharLoginMouseClicked(evt);
            }
        });

        jLabelMinLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMinLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinLogin.setText("-");
        jLabelMinLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(jLabelMinLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFecharLogin)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecharLogin)
                    .addComponent(jLabelMinLogin)
                    .addComponent(jLabel1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 70);

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        jLabelLoginPgLogin.setBackground(new java.awt.Color(44, 62, 80));
        jLabelLoginPgLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelLoginPgLogin.setForeground(new java.awt.Color(236, 240, 241));
        jLabelLoginPgLogin.setText("Login:");

        jLabelSenhaPgLogin.setBackground(new java.awt.Color(44, 62, 80));
        jLabelSenhaPgLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSenhaPgLogin.setForeground(new java.awt.Color(236, 240, 241));
        jLabelSenhaPgLogin.setText("Senha:");

        txtLoginPgLogin.setBackground(new java.awt.Color(108, 122, 137));
        txtLoginPgLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtLoginPgLogin.setForeground(new java.awt.Color(236, 240, 241));
        txtLoginPgLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginPgLoginActionPerformed(evt);
            }
        });

        txtSenhaPgLogin.setBackground(new java.awt.Color(108, 122, 137));
        txtSenhaPgLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSenhaPgLogin.setForeground(new java.awt.Color(236, 240, 241));
        txtSenhaPgLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaPgLoginActionPerformed(evt);
            }
        });

        jButtonCancelarPgLogin.setBackground(new java.awt.Color(192, 57, 43));
        jButtonCancelarPgLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancelarPgLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelarPgLogin.setText("Cancelar");
        jButtonCancelarPgLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarPgLoginActionPerformed(evt);
            }
        });

        jButtonEntrarPgLogin.setBackground(new java.awt.Color(34, 167, 240));
        jButtonEntrarPgLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEntrarPgLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEntrarPgLogin.setText("Entrar");
        jButtonEntrarPgLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarPgLoginActionPerformed(evt);
            }
        });

        cbUsuario.setBackground(new java.awt.Color(108, 122, 137));
        cbUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbUsuario.setForeground(new java.awt.Color(236, 240, 241));
        cbUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Atendente" }));
        cbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabelLoginPgLogin)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtLoginPgLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabelSenhaPgLogin)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtSenhaPgLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarPgLogin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEntrarPgLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLoginPgLogin)
                            .addComponent(txtLoginPgLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSenhaPgLogin)
                            .addComponent(txtSenhaPgLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCancelarPgLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEntrarPgLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 400, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelFecharLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFecharLoginMouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabelFecharLoginMouseClicked

    private void jLabelMinLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinLoginMouseClicked
      this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinLoginMouseClicked

    private void txtLoginPgLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginPgLoginActionPerformed
    
    }//GEN-LAST:event_txtLoginPgLoginActionPerformed

    private void txtSenhaPgLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaPgLoginActionPerformed
       
    }//GEN-LAST:event_txtSenhaPgLoginActionPerformed

    private void cbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUsuarioActionPerformed

    private void jButtonCancelarPgLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarPgLoginActionPerformed
       txtLoginPgLogin.setText("");
       txtSenhaPgLogin.setText("");
       
    }//GEN-LAST:event_jButtonCancelarPgLoginActionPerformed

    private void jButtonEntrarPgLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarPgLoginActionPerformed
String login = txtLoginPgLogin.getText();
String senha = txtSenhaPgLogin.getText();
String usuario = (String) cbUsuario.getSelectedItem();


Login adm = new Login("adm@adm.com" , "123abc");
Login atend = new Login ("atend@atend.com","321abc");
listaLogin.add(adm);
listaLogin.add(atend);


switch(usuario){
    case "Administrador":{ 
        if(txtLoginPgLogin.getText().equals(adm.getLogin()) && txtSenhaPgLogin.getText().equals(adm.getSenha())){
            
    InterfaceAdm iadm = new InterfaceAdm();
        iadm.setVisible(true);
        iadm.pack();
        iadm.setLocationRelativeTo(null);
        iadm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); 
}
else{
JOptionPane.showMessageDialog(null, "Usuário ou senha inválidos", "Erro de Autenticação", JOptionPane.ERROR_MESSAGE);
        }

        
}
    break;
    case "Atendente":{
        if(txtLoginPgLogin.getText().equals(atend.getLogin()) && txtSenhaPgLogin.getText().equals(atend.getSenha())){
            
    InterfaceAtendente iatend = new InterfaceAtendente();
        iatend.setVisible(true);
        iatend.pack();
        iatend.setLocationRelativeTo(null);
        iatend.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); 
}
else{
JOptionPane.showMessageDialog(null, "Usuário ou senha inválidos", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    

}



    



    }//GEN-LAST:event_jButtonEntrarPgLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbUsuario;
    private javax.swing.JButton jButtonCancelarPgLogin;
    private javax.swing.JButton jButtonEntrarPgLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFecharLogin;
    private javax.swing.JLabel jLabelLoginPgLogin;
    private javax.swing.JLabel jLabelMinLogin;
    private javax.swing.JLabel jLabelSenhaPgLogin;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtLoginPgLogin;
    private javax.swing.JPasswordField txtSenhaPgLogin;
    // End of variables declaration//GEN-END:variables
}
