/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import Limitadores.SomenteNumeros;
import USUARIOS.User;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.DefaultListModel;




public class InterfaceADMCadastraCUsuários extends javax.swing.JFrame {
       
        ArrayList<User> listaUser;
        DefaultListModel dlm;
       
         
    /**
     * Creates new form InterfaceAtendenteCadastraCliente
     */
    public InterfaceADMCadastraCUsuários() {
         initComponents();
         this.setLocationRelativeTo(null);
         txtIdade.setDocument(new SomenteNumeros());
        
        listaUser = new ArrayList();
        dlm = new DefaultListModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelFecharLogin = new javax.swing.JLabel();
        jLabelMinLogin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtSenhaPgLogin1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnRemover = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaCadastrados = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDados = new javax.swing.JTextArea();
        cbUsuario = new javax.swing.JComboBox<>();
        bCadastrarCliente1 = new javax.swing.JButton();
        btPgAdm = new javax.swing.JButton();
        txtDtaCdst = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));
        jPanel1.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gerenciamento de Usuários");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 20, 420, 29);

        jLabelFecharLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelFecharLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecharLogin.setText("X");
        jLabelFecharLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFecharLoginMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelFecharLogin);
        jLabelFecharLogin.setBounds(650, 20, 20, 29);

        jLabelMinLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMinLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinLogin.setText("-");
        jLabelMinLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinLoginMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMinLogin);
        jLabelMinLogin.setBounds(630, 20, 10, 29);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 690, 70);

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 240, 241));
        jLabel2.setText("Nome: ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 20, 60, 20);

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));
        jPanel3.setLayout(null);

        txtSenhaPgLogin1.setBackground(new java.awt.Color(108, 122, 137));
        txtSenhaPgLogin1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSenhaPgLogin1.setForeground(new java.awt.Color(236, 240, 241));
        txtSenhaPgLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaPgLogin1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtSenhaPgLogin1);
        txtSenhaPgLogin1.setBounds(51, 14, 201, 28);

        jLabel3.setText("Nome: ");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(6, 14, 38, 16);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(344, 114, 0, 0);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("E-mail:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 70, 60, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("Idade:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 110, 50, 16);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("Dados  ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(520, 10, 60, 16);

        txtNome.setBackground(new java.awt.Color(108, 122, 137));
        txtNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNome.setForeground(new java.awt.Color(236, 240, 241));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel2.add(txtNome);
        txtNome.setBounds(60, 10, 200, 30);

        txtIdade.setBackground(new java.awt.Color(108, 122, 137));
        txtIdade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtIdade.setForeground(new java.awt.Color(236, 240, 241));
        txtIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdadeActionPerformed(evt);
            }
        });
        jPanel2.add(txtIdade);
        txtIdade.setBounds(60, 100, 200, 28);

        txtEmail.setBackground(new java.awt.Color(108, 122, 137));
        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(236, 240, 241));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel2.add(txtEmail);
        txtEmail.setBounds(60, 60, 200, 28);

        btnRemover.setBackground(new java.awt.Color(192, 57, 43));
        btnRemover.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRemover.setForeground(new java.awt.Color(255, 255, 255));
        btnRemover.setText("Excluir");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemover);
        btnRemover.setBounds(120, 190, 90, 32);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 240, 241));
        jLabel8.setText("Nomes dos Usuários");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(300, 10, 150, 17);

        listaCadastrados.setBackground(new java.awt.Color(108, 122, 137));
        listaCadastrados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaCadastrados.setForeground(new java.awt.Color(236, 240, 241));
        listaCadastrados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaCadastradosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listaCadastrados);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(300, 30, 190, 60);

        txtDados.setBackground(new java.awt.Color(108, 122, 137));
        txtDados.setColumns(20);
        txtDados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDados.setForeground(new java.awt.Color(236, 240, 241));
        txtDados.setRows(5);
        jScrollPane4.setViewportView(txtDados);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(510, 30, 170, 190);

        cbUsuario.setBackground(new java.awt.Color(108, 122, 137));
        cbUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbUsuario.setForeground(new java.awt.Color(236, 240, 241));
        cbUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Atendente", "Cliente" }));
        cbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(cbUsuario);
        cbUsuario.setBounds(330, 110, 130, 23);

        bCadastrarCliente1.setBackground(new java.awt.Color(34, 167, 240));
        bCadastrarCliente1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bCadastrarCliente1.setForeground(new java.awt.Color(255, 255, 255));
        bCadastrarCliente1.setText("Cadastrar");
        bCadastrarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastrarCliente1ActionPerformed(evt);
            }
        });
        jPanel2.add(bCadastrarCliente1);
        bCadastrarCliente1.setBounds(220, 190, 100, 32);

        btPgAdm.setBackground(new java.awt.Color(255, 0, 0));
        btPgAdm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPgAdm.setForeground(new java.awt.Color(236, 240, 241));
        btPgAdm.setText("Voltar");
        btPgAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPgAdmActionPerformed(evt);
            }
        });
        jPanel2.add(btPgAdm);
        btPgAdm.setBounds(10, 190, 100, 30);

        txtDtaCdst.setBackground(new java.awt.Color(108, 122, 137));
        txtDtaCdst.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDtaCdst.setForeground(new java.awt.Color(236, 240, 241));
        txtDtaCdst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDtaCdstActionPerformed(evt);
            }
        });
        jPanel2.add(txtDtaCdst);
        txtDtaCdst.setBounds(150, 140, 110, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 240, 241));
        jLabel1.setText("Data de Cadastro:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 150, 140, 17);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 690, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSenhaPgLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaPgLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaPgLogin1ActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed

    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
     
          
        String nome = txtNome.getText();
        dlm.removeElementAt(listaCadastrados.getSelectedIndex());
        txtDados.setText(" ");
        JOptionPane.showMessageDialog(null, "Usuário removido com sucesso", nome, WIDTH);
        

               
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void listaCadastradosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaCadastradosValueChanged
    String nome = listaCadastrados.getSelectedValue();
    
    for(User u :listaUser){
        if(u.getNome().equalsIgnoreCase(nome))
            txtDados.setText(u.imprimirUser());
    }
   
        
    
    }//GEN-LAST:event_listaCadastradosValueChanged

    private void cbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUsuarioActionPerformed

    private void jLabelFecharLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFecharLoginMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelFecharLoginMouseClicked

    private void jLabelMinLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinLoginMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinLoginMouseClicked

    private void bCadastrarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastrarCliente1ActionPerformed

        if(txtNome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo Nome é obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
            
        }
        
         if(txtEmail.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo E-mail é obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
            
        }
         
          if(txtIdade.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo Idade é obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
            
        }
          if(txtDtaCdst.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O campo Data de Cadastro é obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
            
        }
     try{
     String nome = txtNome.getText();
     String email = txtEmail.getText();
     int idade = Integer.parseInt(txtIdade.getText());
     String usuario = cbUsuario.getSelectedItem().toString();
     String dataCadastro = txtDtaCdst.getText();
     String erroIdade = " ";
     
     
     User u = new User(usuario,nome,email,idade,dataCadastro);
     listaUser.add(u);
     dlm.addElement (u.getNome());
     listaCadastrados.setModel(dlm);
     txtNome.setText("");
     txtEmail.setText("");
     txtIdade.setText("");
     txtDtaCdst.setText("");
     }
     catch (NumberFormatException erroIdade){
         JOptionPane.showMessageDialog(null, "Tipo de entrada inválida no Campo Idade" ,"Erro de entrada", JOptionPane.ERROR_MESSAGE);
      } 
     
  
  
  
 
  
  

          
  
  
  
  
 
     
     
     
    
     
     
     
    
     
    
  
  
  
   
     
     

     
     
         
     
  
    }//GEN-LAST:event_bCadastrarCliente1ActionPerformed

    private void btPgAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPgAdmActionPerformed
       
InterfaceAdm iadm = new InterfaceAdm();
        iadm.setVisible(true);
        iadm.pack();
        iadm.setLocationRelativeTo(null);
        iadm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btPgAdmActionPerformed

    private void txtDtaCdstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDtaCdstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDtaCdstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceADMCadastraCUsuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceADMCadastraCUsuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceADMCadastraCUsuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceADMCadastraCUsuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceADMCadastraCUsuários().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bCadastrarCliente1;
    private javax.swing.JButton btPgAdm;
    private javax.swing.JButton btnRemover;
    public javax.swing.JComboBox<String> cbUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFecharLogin;
    private javax.swing.JLabel jLabelMinLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JList<String> listaCadastrados;
    public javax.swing.JTextArea txtDados;
    public javax.swing.JTextField txtDtaCdst;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtIdade;
    public javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenhaPgLogin1;
    // End of variables declaration//GEN-END:variables
}
