/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Interfaces;;
import javax.swing.JOptionPane;
import static java.awt.image.ImageObserver.WIDTH;
import Produtos.Produto;
import javax.swing.JFrame;
import javax.swing.DefaultListModel;

public class InterfaceProduto extends javax.swing.JFrame {

      
      DefaultListModel dlm;
      
Produto p = new Produto ("Bola de Futebol" , "432" , (float) 30,(float) 15);
Produto p2 = new Produto ("Bola de Basquete", "931" , (float) 20, (float) 10);
   
      float soma = p.getPreco() + p2.getPreco();
    /**
     * Creates new form InterfaceProduto
     */
    public InterfaceProduto() {

        initComponents();
       dlm = new DefaultListModel() ;
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableProduto = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFecharLogin = new javax.swing.JLabel();
        jLabelMinLogin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbBasquete = new javax.swing.JRadioButton();
        rbFutebol = new javax.swing.JRadioButton();
        btnLimpar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPedido = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        btnSProd = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnCompra2 = new javax.swing.JButton();
        btnLimpProd1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        tableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "NOME", "PREÇO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableProduto);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("O que deseja comprar?");

        jLabelFecharLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelFecharLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecharLogin.setText("X");
        jLabelFecharLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFecharLoginMouseClicked(evt);
            }
        });

        jLabelMinLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMinLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinLogin.setText("-");
        jLabelMinLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabelMinLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFecharLogin)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecharLogin)
                    .addComponent(jLabelMinLogin)
                    .addComponent(jLabel1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 70);

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setLayout(null);

        rbBasquete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbBasquete.setForeground(new java.awt.Color(236, 240, 241));
        rbBasquete.setText("Bola de Basquete");
        rbBasquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBasqueteActionPerformed(evt);
            }
        });
        jPanel2.add(rbBasquete);
        rbBasquete.setBounds(0, 60, 160, 21);

        rbFutebol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbFutebol.setForeground(new java.awt.Color(236, 240, 241));
        rbFutebol.setText("Bola de Futebol ");
        jPanel2.add(rbFutebol);
        rbFutebol.setBounds(0, 90, 140, 21);

        btnLimpar.setBackground(new java.awt.Color(34, 167, 240));
        btnLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Excluir");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpar);
        btnLimpar.setBounds(110, 260, 80, 32);

        btnSalvar.setBackground(new java.awt.Color(34, 167, 240));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalvar);
        btnSalvar.setBounds(190, 270, 80, 32);

        listaPedido.setBackground(new java.awt.Color(108, 122, 137));
        listaPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaPedido.setForeground(new java.awt.Color(236, 240, 241));
        listaPedido.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                listaPedidoInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaPedido);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(170, 20, 220, 150);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 240, 241));
        jLabel2.setText("Meu Pedido");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(170, 0, 100, 17);

        btnComprar.setBackground(new java.awt.Color(34, 167, 240));
        btnComprar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnComprar.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        jPanel2.add(btnComprar);
        btnComprar.setBounds(280, 280, 100, 32);

        btnSProd.setBackground(new java.awt.Color(0, 102, 102));
        btnSProd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSProd.setForeground(new java.awt.Color(255, 255, 255));
        btnSProd.setText("Salvar item");
        btnSProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSProdActionPerformed(evt);
            }
        });
        jPanel2.add(btnSProd);
        btnSProd.setBounds(180, 200, 120, 23);

        btnVoltar.setBackground(new java.awt.Color(255, 0, 0));
        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(236, 240, 241));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel2.add(btnVoltar);
        btnVoltar.setBounds(0, 200, 80, 20);

        btnCompra2.setBackground(new java.awt.Color(34, 167, 240));
        btnCompra2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCompra2.setForeground(new java.awt.Color(255, 255, 255));
        btnCompra2.setText("Comprar ");
        btnCompra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompra2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCompra2);
        btnCompra2.setBounds(300, 200, 100, 23);

        btnLimpProd1.setBackground(new java.awt.Color(192, 57, 43));
        btnLimpProd1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpProd1.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpProd1.setText("Limpar");
        btnLimpProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpProd1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpProd1);
        btnLimpProd1.setBounds(100, 200, 80, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 400, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelFecharLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFecharLoginMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelFecharLoginMouseClicked

    private void jLabelMinLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinLoginMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinLoginMouseClicked

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
  
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
  
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
      
    }//GEN-LAST:event_btnComprarActionPerformed

    private void rbBasqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBasqueteActionPerformed

    }//GEN-LAST:event_rbBasqueteActionPerformed

    private void listaPedidoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_listaPedidoInputMethodTextChanged
        
    }//GEN-LAST:event_listaPedidoInputMethodTextChanged

      @SuppressWarnings("empty-statement")
    private void btnSProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSProdActionPerformed

        String divisao = "----------------";
        if(!rbBasquete.isSelected() && !rbFutebol.isSelected()){
JOptionPane.showMessageDialog(null,"Selecione um produto", "Aviso", JOptionPane.WARNING_MESSAGE);
}

        if(rbBasquete.isSelected()){
        
          dlm.addElement(p2.imprimir());
          listaPedido.setModel(dlm);
          rbBasquete.setSelected(false);
           
       }
       
        if (rbFutebol.isSelected())     {
        
        dlm.addElement(p.imprimir());
        listaPedido.setModel(dlm);
        rbFutebol.setSelected(false);
        }
    }//GEN-LAST:event_btnSProdActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
     InterfaceAtendente iatend = new InterfaceAtendente();
        iatend.setVisible(true);
        iatend.pack();
        iatend.setLocationRelativeTo(null);
        iatend.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCompra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompra2ActionPerformed

  if(dlm.isEmpty()){
            JOptionPane.showMessageDialog(null, "Lista de Pedidos vazia", "Aviso", HEIGHT);
        }
        else{
        InterfacePagamentoCliente ipc = new InterfacePagamentoCliente();
        ipc.setVisible(true);
        ipc.pack();
        ipc.setLocationRelativeTo(null);
        ipc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
   
  }
    }//GEN-LAST:event_btnCompra2ActionPerformed

    private void btnLimpProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpProd1ActionPerformed
      dlm.removeElementAt(listaPedido.getSelectedIndex());
        listaPedido.clearSelection();
        JOptionPane.showMessageDialog(null, "ítem excluído com sucesso", null, WIDTH);
    }//GEN-LAST:event_btnLimpProd1ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompra2;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnLimpProd1;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSProd;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFecharLogin;
    private javax.swing.JLabel jLabelMinLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> listaPedido;
    private javax.swing.JRadioButton rbBasquete;
    private javax.swing.JRadioButton rbFutebol;
    private javax.swing.JTable tableProduto;
    // End of variables declaration//GEN-END:variables

    private void getElementAt(int i) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
